apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app-deployment
  labels:
    app: library-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
      - name: library-app
        image: vivek08/library-app:latest
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: library-app-secret

---

apiVersion: v1
kind: Service
metadata:
  name: library-app
spec:
  type: NodePort
  selector:
    app: library-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30081

